version: '3'

services:

  postgres:
    image: postgres:16.2-alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'guest'
      POSTGRES_PASSWORD: 'guest'
      POSTGRES_DB: 'content'
    volumes:
      - ./.docker-data/.pg-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-alpine
    container_name: rabbit
    ports:
      - '5672:5672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq/

  s3:
    image: localstack/localstack
    container_name: s3
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-west-1
      PERSISTENCE: 1
    volumes:
      - ./.docker-data/.s3:/var/lib/localstack
      - ./databases/s3:/etc/localstack/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/metrics/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./.docker-data/.prometheus:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: 'guest'
      GF_SECURITY_ADMIN_PASSWORD: 'guest'
    volumes:
      - ./config/metrics/grafana:/etc/grafana/provisioning/datasources
