version: '3'

services:

  postgres:
    image: postgres:16.2-alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'guest'
      POSTGRES_PASSWORD: 'guest'
      POSTGRES_DB: 'content'
    volumes:
      - ./.docker-data/.pg-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-alpine
    container_name: rabbit
    ports:
      - '5672:5672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq/
